# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('DeviceType', models.IntegerField(verbose_name='类型')),
                ('Latitude', models.FloatField(default=0, verbose_name='纬度')),
                ('Longitude', models.FloatField(default=0, verbose_name='经度')),
            ],
        ),
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Description', models.CharField(default=None, max_length=50, verbose_name='描述')),
                ('CreatedTime', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='CameraTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChildType', models.IntegerField(verbose_name='节点类型')),
                ('Cameras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Camera', verbose_name='摄像头')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.CameraGroup', verbose_name='父节点')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Description', models.CharField(default=None, max_length=50, verbose_name='描述')),
                ('Status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Description', models.CharField(default=None, max_length=50, verbose_name='描述')),
                ('Status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='姓名')),
                ('Password', models.CharField(max_length=30, verbose_name='密码')),
                ('Description', models.CharField(default=None, max_length=50, verbose_name='描述')),
                ('RealName', models.CharField(max_length=10, verbose_name='真实姓名')),
                ('Status', models.IntegerField(default=0, verbose_name='状态')),
                ('MaxUpload', models.IntegerField(default=5, verbose_name='最大上传')),
                ('MaxDownload', models.IntegerField(default=5, verbose_name='最大下载')),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Organization', verbose_name='组织')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Role', verbose_name='角色')),
            ],
        ),
        migrations.AddField(
            model_name='cameragroup',
            name='Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.User', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='camera',
            name='Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.User', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='camera',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.CameraGroup', verbose_name='创建时间'),
        ),
        migrations.AlterIndexTogether(
            name='user',
            index_together=set([('Name',)]),
        ),
    ]
