# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20171024_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameragroup',
            name='CreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 6, 18, 4, 371490, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
