# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20171024_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.CameraGroup', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='cameragroup',
            name='CreatedTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 6, 27, 30, 382011, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cameragroup',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='role',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='role',
            name='Status',
            field=models.IntegerField(blank=True, default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
    ]
